### ISSUE TITLE
Get news from user

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#1]
Implement news request for specific user
Format being array of objects in JSON
Max 10 news objects in array

News are the last changed applications from a specific user

A news object contains:
Title of application
Description of application
uid of application

example:
```
[
{
    id: 1234,
    title: "Antrag Sommersportwoche",
    description: "Der Antrag 'Sommersportwoche' wurde von dem AV akzeptiert"
},
{
...
}
]
```

**Comment by mbeierat** [comment]
adapted the Model to further implement this feature in d2a352d

**Comment by mbeierat** [comment]
final implementation in 380087b

This endpoint can be simply called on whilst providing an auth token. Out of this token the username will be read and a maximum of 10 news information will be returned. This will look as follows:

```
[
     {
          "uuid": "0c186a2a-2140-47ed-ab73-10dd87480429",
          "title": "Sommersportwoche",
          "state": 1
     },
     {},{},...
]
```
