### ISSUE TITLE
getTeacher

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#10]
@mbeier-tgm please implement following function ```/getTeacher?id=1234```

Input:
id of the teacher

Output:
```
{
UUID: 1234,
Short: "szakall",
Longname: "Stefan Zakall",
AV: false,
PEK: false,
Administration: false
}
```

**Comment by mbeierat** [comment]
implemented in bb4bf90

The endpoint `/getTeacher` responds to a GET-Request when a query parameter `uuid` containing the uuid of the teacher and a valid access token is provided as authentication.
