### ISSUE TITLE
getPDFs

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#11]
@mbeier-tgm please implement folowing function ```/getPDFs```
token and pdfs being parameters of the get request
Input:
```
token: token,
pdfs: [
{
id: 1234
},
{
id: 2345
},
{
...
}
]
```

Output:
```
{
pdf: "SBFUHBFUS"   // String being the BASE64-Encoded pdf
}
```

**Comment by mbeierat** [comment]
implemented in 0e47883 and 274ec6c
