### ISSUE TITLE
Create login functionality

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#2]
@mbeier-tgm please implement /login?mail='mbeier@tgm.ac.at',pswd='123456789'

This should be structured like the following:
Input:

email of user
password of user

Output:

Information about the user
example:
```
{
success: true,
user: 1234,
admin: true
}
```

**Comment by mbeierat** [comment]
Implemented login system with security auth tokens.

This includes:

- a standalone token management (f265383 and 84ae7cb)
- a login function (043cfbd)
- a logout endpoint (4225b6e)
- an extra auth firewall for endpoints which need authentication (26219ab)
- generating new token set from refresh tokens (fff1938)


The following new endpoints have been added:

- `POST /login`
- `POST /logout`
- `POST /login/refresh`

These can be called as follows:

**Login-Endpoint:**
Via a POST-Request containing a body of `application/json` including the fields

- username
- password

Example:
```
{
     "username": "test",
     "password": "1234"
}
```

Returned will be a response with a body of `application/json` containing the fields

- access_token
- refresh_token

on success, on error an error message will be returned.

This might look like as the following:
```
{
    "access_token": "....",
    "refresh_token": "...."
}
```


**Logout Endpoint:**
This endpoint is protected via the authorization security wall, which means that this will only be callable providing a valid token.
The token must be provided in the `Authorization` Field of the Request. It will then be destroyed on call.



**Login Refresh Endpoint:**

With providing the refresh token as authorization, the token will be destroyed and a new set of valid access and refresh token will be created and returned (for an example see the return of the `/login` - Endpoint)


Notice: To check whether the put in credentials are correct was moved to #13
