### ISSUE TITLE
applications

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#3]
@mbeier-tgm please implement `/application/getApplication?id=`

This should be structured like the following:
Input:
- application id

Output:
JSON-object containing:
- application status
- application links for the documents
- ... all further information huginn is able to provide

**Comment by mbeierat** [comment]
implemented fundamental functionality in the Database Connector to further implement this issue as an endpoint in 8ebf61a

**Comment by mbeierat** [comment]
implemented in 32cfd6f

The GET Endpoint `/getApplication?uuid=` will return an application as `application/json` (for structure see collection.go) if a valid uuid and an auth token is provided
