### ISSUE TITLE
getAllApplications

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#4]
@mbeier-tgm please implement `/getAllApplications[?user=]`

This should be structured like the following:
Input:
 - optional: user id

Output:
 - Array of all application elements
example:
   [
      {
      id: 1234,
      title: "Skiwoche",
      leader: "Stefan Zakall",
      edate: "2018-01-12",
      status: "Angenommen",  (Could be "Angenommen", "Abgelehnt", "In Bearbeitung")
      active: false
      },
      {
      ...
      }
   ]

If user id is specified only return all applications from the specific user

**Comment by mbeierat** [comment]
should this endpoint also return applications in which the specified user is only a participant and not a leader?

**Comment by rfoster93** [comment]
> 
> 
> should this endpoint also return applications in which the specified user is only a participant and not a leader?

Yes, all Applications in which the user is leader or participant should be returned

**Comment by mbeierat** [comment]
implemented a method in the database connector to further implement this issue as an endpoint in c60f0a6

**Comment by mbeierat** [comment]
Final implementation in a102f35

This returns all applications if a security token is provided and the user requesting has the needed permissions (AV, Administration or PEK). Also a filter (short name as `username`) of a teacher might be provided. This will then return all applications of the provided teacher. When a filter is applied a teacher might lookup their own applications permission wise
