### ISSUE TITLE
getActiveApplications

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#5]
@mbeier-tgm please implement /getActiveApplications[?user=]

This should be structured like the following:
Input:

    `optional: user id`

Output:

Array of all application elements

example:
```
[
{
    id: 1234,
    title: "Skiwoche",
    leader: "Stefan Zakall",
    edate: "2018-01-12",
    status: "Angenommen", (Could be "Angenommen", "Abgelehnt", "In Bearbeitung")
    active: false
},
{
...
}
]
```

If user id is specified only return all applications from the specific user

**Comment by mbeierat** [comment]
implemented fundamental functionality in the Database Connector to further implement this issue as an endpoint in 8ebf61a

**Comment by mbeierat** [comment]
Final implementation in 16b7813 and 15cb7df

This returns all active application if a security token is provided and the user requesting has the needed permissions (AV, Administration or PEK). Also a filter (short name as `username`) of a teacher might be provided. This will return then all active applications of the provided teacher. When a filter is applied a teacher might lookup their own applications permission wise)
