### ISSUE TITLE
getAllAdminApplications

### ISSUE THREAD

**Issue by rfoster93** [refundable-tgm/huginn#8]
@mbeier-tgm please implement /getAllAdminApplications?id='1234'

Input:
```
user id
```

Output:
Array of all Applications linked to the admin
```
[
{
    id: 1234,
    title: "Sommersportwoche",
    kind: "Schulveranstaltung",
    status: "Rechnungsphase",
    edate: "2020-12-19",
    start: "2021-06-15",
    from: "brah"
},
{
...
}
]
```

**Comment by mbeierat** [comment]
Implemented in ba6e844

The GET `/getAdminApplications` endpoint returns all applications currently in need for an review by some kind of admin account (Administration, AV, PEK). No further parameters are needed since the username is extracted from the access token, which has to be provided.
